services:
  backend:
    ports: !override
      - "${API_PORT}:${API_PORT}"
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: prod
      tags:
        - "full_stack_template/api:latest"

  frontend:
    ports: !override
      - "80:80"
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: prod
      tags:
        - "full_stack_template/app:latest"
